version: "3.9"
services:
  dbadmin:
    build:
      context: ./pgadmin
    ports:
      - "8001:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    restart: always
    depends_on:
      - db
    env_file:
      - .env